#pragma once

#define TRI_LAYER_LOWER_LAYER 2
#define TRI_LAYER_UPPER_LAYER 3
#define TRI_LAYER_ADJUST_LAYER 4

#define SPLIT_WPM_ENABLE

#define OLED_IC OLED_IC_SSD1312
#define OLED_DISPLAY_128X64
#define OLED_FLIP_SEGMENT
#define OLED_DISPLAY_ADDRESS 0x3C
#define OLED_CHARGE_PUMP_VALUE 0x72 // ???
#define OLED_BRIGHTNESS 64
#define OLED_UPDATE_INTERVAL 50
#define OLED_TIMEOUT 30000
#define OLED_FADE_OUT

#define MASTER_RIGHT

#undef MANUFACTURER
#define MANUFACTURER "mppks"
#undef PRODUCT
#define PRODUCT "Sofle v2 keyboard"
